services:
  axon-server:
    image: axoniq/axonserver
    container_name: axon-server
    ports:
      - "8024:8024"
      - "8124:8124"
    environment:
      - AXONSERVER_HOSTNAME=axon-server
      - AXONSERVER_NAME=MyAxonServer
      - AXONSERVER_DOMAIN=localhost
      - AXONSERVER_EVENTSTORE=jdbc
      - AXONSERVER_EVENTSTORE_USER=kiko
      - AXONSERVER_EVENTSTORE_PASSWORD=kiko
      - AXONSERVER_EVENTSTORE_DBNAME=db
      - AXONSERVER_DEVMODE=true
    volumes:
      - axonserver-data:/data
#  my-service:
#    build: .
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_PROFILES_ACTIVE=dev


#  discovery-server:
#    image: berdievyand/discovery-server:latest
#    container_name: discovery-server
#    ports:
#      - "8761:8761"
#    networks:
#      - spring
#
#  api-gateway:
#    image: berdievyand/discovery-server:latest
#    container_name: api-gateway
#    ports:
#      - "8082:8082"
#    networks:
#      - spring
#    depends_on:
#      - discovery-server
volumes:
  axonserver-data:


